"""fixed timestamp2

Revision ID: 078a8b567392
Revises: c02c73a3066b
Create Date: 2019-10-02 13:27:54.030314

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '078a8b567392'
down_revision = 'c02c73a3066b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('temperature', sa.Column('timestamp', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('temperature', 'timestamp')
    # ### end Alembic commands ###
